apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-app
  namespace: payments
  labels:
    app: payments
    owner: payments
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
        owner: payments
    spec:
      containers:
        - name: app
          image: ghcr.io/nguyenmen04/w10-api:v1.0.0
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
